### PR TITLE
feat: Resizable Panel for Mail tab

### PR DESCRIPTION
**Pull request by Ipriyankrajai**
Adding Resizable Panel for Mail tab

### CODE REVIEW

**Comment by Ipriyankrajai** [comment]
Hey @elie222 ,

I'm facing one issue with EmailPannel. For some reason, overflow-auto is not working for this component.

image

**Comment by elie222** [comment]
Thank @Ipriyankrajai.

Just need to sign CLA and fix lock.yaml

**Comment by elie222** [comment]
Sorry, merge conflict again :(

**Comment by Ipriyankrajai** [comment]
Hello @elie222 ,
Sorted merge conflict. But Im still not able to sign the cla

**Pull request merged**
