### PR TITLE
Fix: mail navigation

### PR DESCRIPTION
**Pull request by Ipriyankrajai**
Fix: #125

### CODE REVIEW

**Comment by Ipriyankrajai** [comment]
Fix: #127

**Comment by elie222** [comment]
This changes README too (and not sure in ways it needs to be changed).

For the bug itself, where does it happen to you? Because it links me to these pages correctly: https://www.getinboxzero.com/mail?type=sent

**Comment by Ipriyankrajai** [comment]
First go to compose page than then try to go to mail or draft page

**Comment by Ipriyankrajai** [comment]
By changing readme i tried to Fix: #127

**Comment by elie222** [comment]
> First go to compose page than then try to go to mail or draft page

Ah okay. I actually got rid of compose page now. For multiple changes it would be better to have it as two different PRs

**Comment by elie222** [comment]
Also about the README, Redis is something you want to set if you're deploying it. Db url is too. So maybe I should make that more clear.

**Pull request closed without merging**
