### PR TITLE
compose: multiselect for recipient field

### PR DESCRIPTION
**Pull request by ajmalwashere**
Added mutiselect for compose recipient field.

using headless ui as planned because shadcn doesn't support multi select in combobox.

i also noticed headless ui combobox doesn't support editable dropdown. we need that for typing or copy pasting email address :) Refer -> (https://github.com/tailwindlabs/headlessui/discussions/1228)

need to decide how to proceed from here for adding editable field -> try workaround or use another component

Xnapper-2024-01-09-05 00 03

### CODE REVIEW

**Comment by elie222** [comment]
`Allow Custom Values` doesn't solve the problem?
https://headlessui.com/react/combobox#allowing-custom-values

Okay going with another library if HUI doesn't do everything we need.

**Comment by elie222** [comment]
Ah, I see that link is mentioned a few times in the issue you linked to. And it's limiting.

Some features we'd want for an email client:

* Supports free form text
* Supports multi select
* Full control of styling so it can look something like we're used to in email clients (eg Gmail)

Worth taking a look at alternative libraries that offer this.

**Comment by elie222** [comment]
Two potential libraries:
https://www.npmjs.com/package/react-select
https://www.npmjs.com/package/downshift

**Comment by ajmalwashere** [comment]
@elie222 I have used the workaround with invisible `Combobox.Option`.

You give it a try locally and see if its fits all requirements. 

I used zod to validate if its valid email

**Comment by elie222** [comment]
Great. Thanks!

When no search result is found we should not show the dropdown:
image

For styling, I think we can try without any border shown. Similar to what you have in other email clients.  But also will impact on how much we can style Novel editor. If it's limited right now maybe we just keep the other inputs the same style as Novel.

Styling from two other email editors for inspiration:
CleanShot 2024-01-09 at 11 15 53@2x
CleanShot 2024-01-09 at 11 16 48@2x

**Pull request merged**
