### PR TITLE
Novel 2 upgrade

### PR DESCRIPTION
**Pull request by elie222**
This doesn't work right now. Opened the PR to share on Novel GitHub.

### CODE REVIEW

**Comment by andrewdoro** [comment]
Hey you are missing the extensions config 
https://novel.sh/docs/guides/tailwind/setup#configure-extensions

**Comment by elie222** [comment]
> Hey you are missing the extensions config [novel.sh/docs/guides/tailwind/setup#configure-extensions](https://novel.sh/docs/guides/tailwind/setup#configure-extensions)

Thanks! Probably worth noting in the quick start as many people will be using Tailwind with this package.
Another dev started working on this feature and ran into the same issue btw.

We assumed the problem was that the project was still in flux rather than something we could fix.

**Comment by elie222** [comment]
That wasn't the issue. This is the issue:
CleanShot 2024-02-23 at 09 42 25@2x

**Comment by elie222** [comment]
Also unclear to me how the most basic example should work. As the TypeScript expects a child component here:
CleanShot 2024-02-23 at 09 44 34@2x

**Comment by elie222** [comment]
Once setting to Bundler resolution, this is the error that appears:
CleanShot 2024-02-23 at 09 54 43@2x

**Comment by elie222** [comment]
> Once setting to Bundler resolution, this is the error that appears: CleanShot 2024-02-23 at 09 54 43@2x

Okay. Adding `extensions` causes that error to go away.

I now have something to work with. I'll get the update out. Thanks for the help.

**Comment by andrewdoro** [comment]
Hey no problem if you have any more problems you can write me on twitter. Currently I still have to get the docs right, I am open to any feedback.

**Comment by elie222** [comment]
> Hey no problem if you have any more problems you can write me on twitter. Currently I still have to get the docs right, I am open to any feedback.

Will do!

Made a few more commits. This one fixed TS errors:
[`ca51798` (#145)](https://github.com/elie222/inbox-zero/pull/145/commits/ca51798e3ba661ee7f51a814850dc7c5c2ec7175)

Might be worth changing your example project to `strict` mode.

**Comment by elie222** [comment]
Got it working now. Thanks for the help.

CleanShot 2024-02-23 at 10 43 43@2x

**Comment by andrewdoro** [comment]
Nice, keep in mind that the AI features would be changed with this PR
https://github.com/steven-tey/novel/pull/297

**Comment by elie222** [comment]
> Nice, keep in mind that the AI features would be changed with this PR [steven-tey/novel#297](https://github.com/steven-tey/novel/pull/297)

Thanks. I've disabled the AI for now. I saw it didn't look right and noticed the PR.

**Pull request merged**
